stages:
  - deploy

variables:
  APP_NAME: team-project-4
  SSH_HOST: "172.23.66.238"  # 确保这里设置为正确的远程服务器地址

deploy:
  image: python:3.10
  stage: deploy
  environment:
    name: production
    url: http://172.23.66.238:58062
  only:
    - main
  before_script:
    - pip install Cython
    - pip show Cython  # 确保 Cython 已正确安装
    - apt-get update && apt-get install -y build-essential git
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "Host $SSH_HOST" >> ~/.ssh/config
    - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - git checkout main
    - git push ssh://dokku@172.23.66.238:22/team-project-4

