stages:
  - deploy

variables:
  APP_NAME: team-project-4

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: http://172.23.66.238:58062
  only:
    - main
  before_script:
    # 安装 Python 和 pip
    - apt-get update && apt-get install -y python3 python3-pip
    # 安装 Cython 和构建工具
    - pip3 install Cython
    - apt-get install -y build-essential
  script:
    - git-push ssh://dokku@172.23.66.238:22/team-project-4

