stages:
  - deploy

variables:
  APP_NAME: team-project-4

deploy:
  image: python:3.10  # 使用 Python 官方镜像
  stage: deploy
  environment:
    name: production
    url: http://172.23.66.238:58062
  only:
    - main
  before_script:
    # 安装 Cython 和构建工具
    - pip install Cython
    - apt-get update && apt-get install -y build-essential git
  script:
    # 切换到 main 分支并推送
    - git checkout main  # 切换到 main 分支
    - git push ssh://dokku@172.23.66.238:22/team-project-4

