stages:
  - deploy

variables:
  APP_NAME: team-project-4
  GIT_DEPTH: 0  # 拉取完整历史

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: http://172.23.66.238:58062
  only:
    - main
  script:
    - git checkout main  # 确保切换到 main 分支
    - git-push ssh://dokku@172.23.66.238:22/team-project-4 main:main